sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  aliyun:
    oss:
      bucket-name: sky-take-out-myl
      endpoint: oss-cn-hangzhou.aliyuncs.com
      region: cn-hangzhou

